package app.completion

import app.storage.isDevMode
import app.storage.storageRoot
import com.github.ajalt.clikt.completion.CompletionGenerator
import commands.MainCommand
import es.jvbabi.kfile.File
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.toKString
import platform.posix.getenv

@OptIn(ExperimentalForeignApi::class)
fun setupCompletions(command: MainCommand) {
    val shellPath = getenv("SHELL")?.toKString() ?: "/bin/zsh"
    val shellName = when {
        shellPath.endsWith("zsh") -> "zsh"
        shellPath.endsWith("bash") -> "bash"
        else -> "zsh"
    }

    // Paths under storage root
    val completionsDir = storageRoot.resolve("completions").apply { if (!exists()) mkdir() }
    val completionFile = completionsDir.resolve("wb.$shellName")
    val watcherScript = storageRoot.resolve("watch-completions.sh")

    // Generate completion script on every run
    val completionScript = CompletionGenerator.generateCompletionForCommand(command,
        if (shellName.endsWith("zsh")) "/bin/zsh" else "/bin/bash"
    )
    completionFile.writeText(completionScript)

    // Create/update watcher script (idempotent content rewrite)
    val watcherContent = buildString {
        appendLine("# Generated by Werkbank CLI - do not edit manually")
        appendLine("# Sources completion file when it changes (checked every 2s)")
        appendLine("WB_COMPLETION_FILE=\"${completionFile.absolutePath}\"")
        appendLine("_wb_hash_cmd() { if command -v shasum >/dev/null 2>&1; then shasum -a 1 \"${'$'}1\" | awk '{print ${'$'}1}'; elif command -v sha1sum >/dev/null 2>&1; then sha1sum \"${'$'}1\" | awk '{print ${'$'}1}'; elif command -v md5 >/dev/null 2>&1; then md5 -q \"${'$'}1\"; else echo \"\"; fi; }")
        appendLine("_wb_last_hash=\"\"")
        appendLine("_wb_last_checked=0")
        appendLine("_wb_interval=2")
        appendLine(
            """
            |_wb_check_and_source() {
            |  local now hash
            |  now=
            |  now=$(date +%s)
            |  if [ $((${ '$' }now - ${ '$' }_wb_last_checked)) -lt ${ '$' }_wb_interval ]; then return; fi
            |  _wb_last_checked=${ '$' }now
            |  if [ -f "${ '$' }WB_COMPLETION_FILE" ]; then
            |    hash=$(_wb_hash_cmd "${ '$' }WB_COMPLETION_FILE")
            |    if [ "${ '$' }hash" != "${ '$' }_wb_last_hash" ]; then
            |      _wb_last_hash="${ '$' }hash"
            |      . "${ '$' }WB_COMPLETION_FILE"
            |    fi
            |  fi
            |}
            |if [ -n "${ '$' }ZSH_VERSION" ]; then
            |  autoload -Uz add-zsh-hook 2>/dev/null
            |  if command -v add-zsh-hook >/dev/null 2>&1; then
            |    add-zsh-hook precmd _wb_check_and_source 2>/dev/null || true
            |  else
            |    typeset -ga precmd_functions
            |    precmd_functions+=(_wb_check_and_source)
            |  fi
            |else
            |  case "${ '$' }PROMPT_COMMAND" in
            |    *"_wb_check_and_source"*) : ;;
            |    *) PROMPT_COMMAND="_wb_check_and_source; ${ '$' }PROMPT_COMMAND" ;;
            |  esac
            |fi
            |""".trimMargin()
        )
    }
    watcherScript.writeText(watcherContent)

    // In prod mode, add sourcing line once to the appropriate shell rc
    if (!isDevMode) {
        val home = File.getUserHomeDirectory()
        val rcFile = when (shellName) {
            "zsh" -> home.resolve(".zshrc")
            else -> home.resolve(".bashrc")
        }
        if (!rcFile.exists()) rcFile.writeText("")

        val sourceLine = "# Werkbank completions watcher\n. \"${watcherScript.absolutePath}\"\n"
        val current = rcFile.readText()
        if (!current.contains(watcherScript.absolutePath)) {
            rcFile.writeText(current + "\n" + sourceLine)
        }
    }
}
