package commands.certificates

import app.data.Project
import app.dependencies.AppDependency
import app.dependencies.openssl.OpensslHandler
import app.repository.ProjectRepository
import es.jvbabi.kfile.File
import org.koin.core.component.KoinComponent
import org.koin.core.component.inject
import org.koin.core.qualifier.named

/**
 * How badly a certificate is off. [OUTDATED] means the certificate itself is intact but no longer
 * matches the current setup (root CA or domains changed), [BROKEN] means files are missing or do
 * not belong together.
 */
internal enum class CertificateStatus { VALID, OUTDATED, BROKEN }

internal data class Finding(val title: String, val detail: String, val status: CertificateStatus)

/**
 * @param name what the certificate is called in the report
 * @param key how the certificate is addressed on the command line, `null` when it cannot be
 *   regenerated by werkbank
 * @param domains the domains the certificate is expected to cover
 */
internal data class CertificateEntry(
    val name: String,
    val key: String?,
    val domains: List<String>,
    val findings: List<Finding>
) {
    val status = findings.maxOfOrNull { it.status } ?: CertificateStatus.VALID
    val isValid get() = status == CertificateStatus.VALID
}

/** Everything that has to happen to get all certificates back to [CertificateStatus.VALID]. */
internal data class RepairPlan(
    val regenerateRoot: Boolean,
    val installRoot: Boolean,
    val serviceKeys: List<String>,
    val projectIds: List<String>,
    val allServices: Boolean,
    val allProjects: Boolean
) {
    val isEmpty get() = !regenerateRoot && !installRoot && serviceKeys.isEmpty() && projectIds.isEmpty()

    /** The `certificates` subcommands that carry out this plan, in the order they have to run. */
    val commands: List<String>
        get() = buildList {
            if (regenerateRoot) {
                add("generate all")
                return@buildList
            }
            if (installRoot) add("install")

            val arguments = buildList {
                if (allServices) add("--services")
                else if (serviceKeys.isNotEmpty()) add("--service=${serviceKeys.joinToString(",")}")
                if (allProjects) add("--projects")
                else if (projectIds.isNotEmpty()) add("--project=${projectIds.joinToString(",")}")
            }
            if (arguments.isNotEmpty()) add("generate ${arguments.joinToString(" ")}")
        }
}

/** Reads the certificates from disk and judges them, without printing anything. */
internal class CertificateInspector : KoinComponent {
    private val opensslHandler by inject<OpensslHandler>()
    private val dependencies by inject<List<AppDependency>>(named("Dependencies"))
    private val projectRepository by inject<ProjectRepository>()

    fun inspectRootCa(): CertificateEntry {
        val certificateFile = opensslHandler.rootCaFile
        val findings = mutableListOf<Finding>()

        findings += inspect(
            certificateFile = certificateFile,
            privateKeyFile = opensslHandler.rootKeyFile,
            expectedDomains = opensslHandler.rootCaDomains,
            checkSignedByRootCa = false
        )

        if (!opensslHandler.keyStoreFile.exists()) {
            findings += Finding(
                "keystore missing",
                opensslHandler.keyStoreFile.absolutePath,
                CertificateStatus.BROKEN
            )
        }

        if (certificateFile.exists() && !OpensslHandler.isTrusted(certificateFile)) {
            findings += Finding(
                NOT_TRUSTED,
                "the root CA is not installed in the system",
                CertificateStatus.OUTDATED
            )
        }

        return CertificateEntry(certificateFile.name, null, opensslHandler.rootCaDomains, findings)
    }

    fun inspectServices() = dependencies
        .filter { it.webfacingDomains.isNotEmpty() }
        .map { dependency ->
            CertificateEntry(
                name = dependency.key,
                key = dependency.key,
                domains = dependency.webfacingDomains,
                findings = inspect(
                    certificateFile = opensslHandler.certificateFileOf(dependency),
                    privateKeyFile = opensslHandler.privateKeyFileOf(dependency),
                    expectedDomains = dependency.webfacingDomains
                )
            )
        }

    fun inspectProjects() = projectRepository.getAllProjects().map { inspectProject(it) }

    private fun inspectProject(project: Project): CertificateEntry {
        val werkbankfile = File(project.path).resolve("Werkbankfile.yaml")
        if (!werkbankfile.exists()) return CertificateEntry(
            name = project.id,
            key = project.id,
            domains = emptyList(),
            findings = listOf(
                Finding("Werkbankfile missing", werkbankfile.absolutePath, CertificateStatus.BROKEN)
            )
        )

        val domains = project.getCertificateDomains()
        return CertificateEntry(
            name = project.id,
            key = project.id,
            domains = domains,
            findings = inspect(
                certificateFile = project.certificateFile,
                privateKeyFile = project.privateKeyFile,
                expectedDomains = domains
            )
        )
    }

    /**
     * Imported certificates are signed by a foreign CA and were issued for domains werkbank does
     * not know, so only the parts that can be judged locally are checked: both files are there,
     * they belong together and the certificate is still valid.
     */
    fun inspectExternalCertificates(): List<CertificateEntry> {
        val directory = opensslHandler.externalCertificateDirectory
        if (!directory.exists()) return emptyList()

        return directory.listFiles()
            .filter { it.name.endsWith(".crt") }
            .sortedBy { it.name }
            .map { certificateFile ->
                val privateKeyFile = directory.resolve("${certificateFile.nameWithoutExtension}.key")
                val findings = mutableListOf<Finding>()

                if (!privateKeyFile.exists()) {
                    findings += Finding(
                        "private key missing",
                        privateKeyFile.absolutePath,
                        CertificateStatus.BROKEN
                    )
                } else if (!OpensslHandler.isValidPair(certificateFile, privateKeyFile)) {
                    findings += Finding(
                        "key mismatch",
                        "certificate and private key do not belong together",
                        CertificateStatus.BROKEN
                    )
                }

                if (OpensslHandler.isExpired(certificateFile)) {
                    findings += Finding(
                        "expired",
                        "the certificate has to be imported again",
                        CertificateStatus.OUTDATED
                    )
                }

                CertificateEntry(
                    name = certificateFile.absolutePath,
                    key = null,
                    domains = OpensslHandler.getDomains(certificateFile),
                    findings = findings
                )
            }
    }

    /**
     * Runs all checks that apply to a certificate and its private key. Checks that build on an
     * earlier one are skipped instead of reported twice, e.g. domains are only compared once the
     * certificate is known to exist.
     */
    private fun inspect(
        certificateFile: File,
        privateKeyFile: File,
        expectedDomains: List<String>,
        checkSignedByRootCa: Boolean = true
    ): List<Finding> {
        val findings = mutableListOf<Finding>()

        if (!certificateFile.exists()) {
            findings += Finding("certificate missing", certificateFile.absolutePath, CertificateStatus.BROKEN)
        }
        if (!privateKeyFile.exists()) {
            findings += Finding("private key missing", privateKeyFile.absolutePath, CertificateStatus.BROKEN)
        }
        if (findings.isNotEmpty()) return findings

        if (!OpensslHandler.isValidPair(certificateFile, privateKeyFile)) {
            findings += Finding(
                "key mismatch",
                "certificate and private key do not belong together",
                CertificateStatus.BROKEN
            )
        }

        val actualDomains = OpensslHandler.getDomains(certificateFile)
        val missingDomains = expectedDomains - actualDomains.toSet()
        if (missingDomains.isNotEmpty()) {
            findings += Finding("not covered", missingDomains.joinToString(", "), CertificateStatus.OUTDATED)
            findings += Finding(
                "issued for",
                actualDomains.ifEmpty { listOf("nothing") }.joinToString(", "),
                CertificateStatus.OUTDATED
            )
        }

        if (checkSignedByRootCa && !OpensslHandler.isValidChild(opensslHandler.rootCaFile, certificateFile)) {
            findings += Finding(
                "wrong signature",
                "signed by a different root CA or expired",
                CertificateStatus.OUTDATED
            )
        }

        return findings
    }

    /**
     * A root CA that is not usable invalidates every certificate signed by it, so in that case
     * everything is regenerated. A root CA that is merely unknown to the system is intact and
     * only has to be installed. Everything else is repaired certificate by certificate, so the
     * intact ones keep their current key.
     */
    fun repairPlan(
        rootEntry: CertificateEntry,
        serviceEntries: List<CertificateEntry>,
        projectEntries: List<CertificateEntry>
    ): RepairPlan {
        val onlyMissesInstallation = rootEntry.findings.isNotEmpty() &&
                rootEntry.findings.all { it.title == NOT_TRUSTED }

        if (!rootEntry.isValid && !onlyMissesInstallation) return RepairPlan(
            regenerateRoot = true,
            installRoot = false,
            serviceKeys = emptyList(),
            projectIds = emptyList(),
            allServices = true,
            allProjects = true
        )

        val affectedServices = serviceEntries.filterNot { it.isValid }
        val affectedProjects = projectEntries.filterNot { it.isValid }

        return RepairPlan(
            regenerateRoot = false,
            installRoot = onlyMissesInstallation,
            serviceKeys = affectedServices.mapNotNull { it.key },
            projectIds = affectedProjects.mapNotNull { it.key },
            allServices = affectedServices.isNotEmpty() && affectedServices.size == serviceEntries.size,
            allProjects = affectedProjects.isNotEmpty() && affectedProjects.size == projectEntries.size
        )
    }

    private companion object {
        const val NOT_TRUSTED = "not trusted"
    }
}
