name: build_cli.yml
on:
  push:
    branches:
      - main
    paths:
      - 'cli/**'
      - 'mosaic/**'
      - '.github/workflows/build_cli.yml'
  workflow_dispatch: {}

jobs:
  setup:
    name: Generate Build Metadata
    runs-on: ubuntu-latest
    outputs:
      build_tag: ${{ steps.vars.outputs.build_tag }}
      build_timestamp: ${{ steps.vars.outputs.build_timestamp }}
      date_formatted: ${{ steps.vars.outputs.date_formatted }}
    steps:
      - name: Generate vars
        id: vars
        run: |
          TIMESTAMP=$(date +%s)
          TAG=$(date -d @$TIMESTAMP '+%Y%m%d_%H%M')
          DATE_FORMATTED=$(date -d @$TIMESTAMP '+%d.%m.%Y %H:%M')
          echo "build_timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "build_tag=$TAG" >> $GITHUB_OUTPUT
          echo "date_formatted=$DATE_FORMATTED" >> $GITHUB_OUTPUT


  build:
    name: Build CLI Executable
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x64
            gradle-task: ":cli:linkReleaseExecutableLinuxX64"
            artifact-path: "cli/build/bin/linuxX64/releaseExecutable/cli.kexe"
            mosaic-native-target: "LinuxX64"

          - os: ubuntu-latest
            name: linux-arm64
            gradle-task: ":cli:linkReleaseExecutableLinuxArm64"
            artifact-path: "cli/build/bin/linuxArm64/releaseExecutable/cli.kexe"
            mosaic-native-target: "LinuxArm64"

          - os: macos-latest
            name: macos-arm64
            gradle-task: ":cli:linkReleaseExecutableMacosArm64"
            artifact-path: "cli/build/bin/macosArm64/releaseExecutable/cli.kexe"
            mosaic-native-target: "MacosArm64"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '26'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle.kts
            **/*.gradle
            **/gradle.properties
            **/libs.versions.toml

      - name: Get mosaic submodule commit hash
        id: mosaic-hash
        run: echo "hash=$(git ls-tree HEAD mosaic | awk '{print $3}')" >> $GITHUB_OUTPUT

      - name: Cache Mosaic prebuilt artifacts
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/com/jakewharton/mosaic
          key: mosaic-${{ runner.os }}-${{ steps.mosaic-hash.outputs.hash }}

      - name: Configure
        run: echo "cli.dev=false" >> local.properties

      - name: Precompile Mosaic
        working-directory: ./mosaic
        run: |
          ./gradlew publishKotlinMultiplatformPublicationToMavenLocal publish${{ matrix.mosaic-native-target }}PublicationToMavenLocal \
            -PsignAllPublications=false \
            -x :mosaic-tty:jvmJniZigBuild \
            -x spotlessKotlinCheck -x spotlessKotlinApply \
            -x dokkaHtml -x dokkaJavadoc -x dokkaGfm \
            -x apiCheck \
            --no-daemon

      - name: Build CLI
        run: ./gradlew ${{ matrix.gradle-task }} --no-daemon

      - run: mkdir out

      - name: Rename artifact
        run: mv ${{ matrix.artifact-path }} out/cli-${{ matrix.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: cli-${{ matrix.name }}
          path: out/cli-${{ matrix.name }}

  release:
    name: Create Release
    needs: [ build, setup ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: cli-*/**/*
          draft: false
          prerelease: false
          make_latest: true
          name: Werkbank (${{ needs.setup.outputs.date_formatted }})
          fail_on_unmatched_files: true
          tag_name: v${{ needs.setup.outputs.build_tag }}
